---
packages:
  - packages/*
catalogs:
  dev:
    '@dcloudio/uni-cli-shared': 3.0.0-4050520250307001
    '@dcloudio/uni-stacktracey': 3.0.0-4050520250307001
    '@dcloudio/vite-plugin-uni': 3.0.0-4050520250307001
    '@lincy/eslint-config': ^5.5.0
    '@lincy/stylelint-config': ^2.0.1
    '@lincy/uniapp-ui-resolver': ^1.2.1
    '@lincy/unocss-base-config': ^2.2.1
    '@unocss/eslint-plugin': ^65.5.0
    '@vue-macros/volar': ^0.30.15
    eslint: ^9.22.0
    eslint-plugin-format: ^1.0.1
    lint-staged: ^15.4.3
    pnpm: ^10.6.2
    postcss: ^8.5.3
    postcss-px-to-viewport-8-plugin: ^1.2.5
    sass: ^1.85.1
    simple-git-hooks: ^2.11.1
    typescript: 5.6.3
    unocss: ^65.5.0
    unocss-applet: ^0.9.0
    unplugin-auto-import: ^19.1.1
    unplugin-vue-components: ^28.4.1
    unplugin-vue-macros: ^2.14.5
    vite: ^6.2.1
    vue-tsc: ^2.2.8
  prod:
    '@dcloudio/uni-app': 3.0.0-4050520250307001
    '@dcloudio/uni-app-plus': 3.0.0-4050520250307001
    '@dcloudio/uni-components': 3.0.0-4050520250307001
    '@dcloudio/uni-h5': 3.0.0-4050520250307001
    '@dcloudio/uni-mp-weixin': 3.0.0-4050520250307001
    '@dcloudio/uni-ui': ^1.5.7
    '@iconify-json/carbon': ^1.2.8
    '@iconify-json/line-md': ^1.2.5
    '@iconify-json/mdi': ^1.2.3
    '@iconify-json/svg-spinners': ^1.2.2
    '@lincy/async-validation': ^1.3.0
    '@lincy/tnui-vue3-uniapp': ^1.0.21
    '@lincy/utils': ^0.6.2
    '@tuniao/tn-icon': ^1.11.0
    '@tuniao/tn-style': ^1.0.20
    '@tuniao/tnui-vue3-uniapp': ^1.0.22
    '@unhead/vue': ^1.11.20
    '@uni-helper/uni-use': ^0.19.14
    '@uni-helper/vite-plugin-uni-components': ^0.2.0
    '@uni-helper/vite-plugin-uni-layouts': ^0.1.10
    '@uni-helper/vite-plugin-uni-pages': ^0.2.28
    '@vue/compiler-sfc': ^3.5.13
    '@vueuse/core': ^13.0.0
    axios: ^1.8.2
    fant-axios-adapter: ^0.0.6
    pinia: 2.3.0
    unhead: ^1.11.20
    vue: 3.5.13
    we-cropper: ^1.4.0
    wot-design-uni: ^1.7.1
  types:
    '@dcloudio/types': ^3.4.14
    '@types/node': ^22.13.10
    '@uni-helper/uni-app-types': 1.0.0-alpha.6
    miniprogram-api-typings: ^4.0.5
