/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EmptyComponents: typeof import('./components/empty-components.vue')['default']
    EmptyPopup: typeof import('./components/empty-popup.vue')['default']
    IsEmpty: typeof import('./components/is-empty.vue')['default']
    Layout: typeof import('./components/layout.vue')['default']
    LcyCheckbox: typeof import('./components/lcy-checkbox.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TnButton: typeof import('@tuniao/tnui-vue3-uniapp/components/button/src/button.vue')['TnButton']
    TnCheckbox: typeof import('@tuniao/tnui-vue3-uniapp/components/checkbox/src/checkbox.vue')['TnCheckbox']
    TnIcon: typeof import('@tuniao/tnui-vue3-uniapp/components/icon/src/icon.vue')['TnIcon']
    TnLoading: typeof import('@tuniao/tnui-vue3-uniapp/components/loading/src/loading.vue')['TnLoading']
    TnPhotoAlbum: typeof import('@tuniao/tnui-vue3-uniapp/components/photo-album/src/photo-album.vue')['TnPhotoAlbum']
    TnPopup: typeof import('@tuniao/tnui-vue3-uniapp/components/popup/src/popup.vue')['TnPopup']
    TnScrollList: typeof import('@tuniao/tnui-vue3-uniapp/components/scroll-list/src/scroll-list.vue')['TnScrollList']
    WdButton: typeof import('wot-design-uni/components/wd-button/wd-button.vue')['WdButton']
    WdCell: typeof import('wot-design-uni/components/wd-cell/wd-cell.vue')['WdCell']
    WdCellGroup: typeof import('wot-design-uni/components/wd-cell-group/wd-cell-group.vue')['WdCellGroup']
    WdForm: typeof import('wot-design-uni/components/wd-form/wd-form.vue')['WdForm']
    WdIcon: typeof import('wot-design-uni/components/wd-icon/wd-icon.vue')['WdIcon']
    WdInput: typeof import('wot-design-uni/components/wd-input/wd-input.vue')['WdInput']
    WdLoading: typeof import('wot-design-uni/components/wd-loading/wd-loading.vue')['WdLoading']
    WdLoadmore: typeof import('wot-design-uni/components/wd-loadmore/wd-loadmore.vue')['WdLoadmore']
    WdNavbar: typeof import('wot-design-uni/components/wd-navbar/wd-navbar.vue')['WdNavbar']
    WdNavbarCapsule: typeof import('wot-design-uni/components/wd-navbar-capsule/wd-navbar-capsule.vue')['WdNavbarCapsule']
    WdPopup: typeof import('wot-design-uni/components/wd-popup/wd-popup.vue')['WdPopup']
    WdStatusTip: typeof import('wot-design-uni/components/wd-status-tip/wd-status-tip.vue')['WdStatusTip']
    WdSwiper: typeof import('wot-design-uni/components/wd-swiper/wd-swiper.vue')['WdSwiper']
  }
}

// For TSX support
declare global {
  const EmptyComponents: typeof import('./components/empty-components.vue')['default']
  const EmptyPopup: typeof import('./components/empty-popup.vue')['default']
  const IsEmpty: typeof import('./components/is-empty.vue')['default']
  const Layout: typeof import('./components/layout.vue')['default']
  const LcyCheckbox: typeof import('./components/lcy-checkbox.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TnButton: typeof import('@tuniao/tnui-vue3-uniapp/components/button/src/button.vue')['TnButton']
  const TnCheckbox: typeof import('@tuniao/tnui-vue3-uniapp/components/checkbox/src/checkbox.vue')['TnCheckbox']
  const TnIcon: typeof import('@tuniao/tnui-vue3-uniapp/components/icon/src/icon.vue')['TnIcon']
  const TnLoading: typeof import('@tuniao/tnui-vue3-uniapp/components/loading/src/loading.vue')['TnLoading']
  const TnPhotoAlbum: typeof import('@tuniao/tnui-vue3-uniapp/components/photo-album/src/photo-album.vue')['TnPhotoAlbum']
  const TnPopup: typeof import('@tuniao/tnui-vue3-uniapp/components/popup/src/popup.vue')['TnPopup']
  const TnScrollList: typeof import('@tuniao/tnui-vue3-uniapp/components/scroll-list/src/scroll-list.vue')['TnScrollList']
  const WdButton: typeof import('wot-design-uni/components/wd-button/wd-button.vue')['WdButton']
  const WdCell: typeof import('wot-design-uni/components/wd-cell/wd-cell.vue')['WdCell']
  const WdCellGroup: typeof import('wot-design-uni/components/wd-cell-group/wd-cell-group.vue')['WdCellGroup']
  const WdForm: typeof import('wot-design-uni/components/wd-form/wd-form.vue')['WdForm']
  const WdIcon: typeof import('wot-design-uni/components/wd-icon/wd-icon.vue')['WdIcon']
  const WdInput: typeof import('wot-design-uni/components/wd-input/wd-input.vue')['WdInput']
  const WdLoading: typeof import('wot-design-uni/components/wd-loading/wd-loading.vue')['WdLoading']
  const WdLoadmore: typeof import('wot-design-uni/components/wd-loadmore/wd-loadmore.vue')['WdLoadmore']
  const WdNavbar: typeof import('wot-design-uni/components/wd-navbar/wd-navbar.vue')['WdNavbar']
  const WdNavbarCapsule: typeof import('wot-design-uni/components/wd-navbar-capsule/wd-navbar-capsule.vue')['WdNavbarCapsule']
  const WdPopup: typeof import('wot-design-uni/components/wd-popup/wd-popup.vue')['WdPopup']
  const WdStatusTip: typeof import('wot-design-uni/components/wd-status-tip/wd-status-tip.vue')['WdStatusTip']
  const WdSwiper: typeof import('wot-design-uni/components/wd-swiper/wd-swiper.vue')['WdSwiper']
}