/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    EmptyComponents: typeof import('./components/empty-components.vue')['default']
    EmptyPopup: typeof import('./components/empty-popup.vue')['default']
    IsEmpty: typeof import('./components/is-empty.vue')['default']
    Layout: typeof import('./components/layout.vue')['default']
    LcyCheckbox: typeof import('./components/lcy-checkbox.vue')['default']
    TnButton: typeof import('@tuniao/tnui-vue3-uniapp/components/button/src/button.vue')['default']
    TnCheckbox: typeof import('@tuniao/tnui-vue3-uniapp/components/checkbox/src/checkbox.vue')['default']
    TnEmpty: typeof import('@tuniao/tnui-vue3-uniapp/components/empty/src/empty.vue')['default']
    TnForm: typeof import('@tuniao/tnui-vue3-uniapp/components/form/src/form.vue')['default']
    TnFormItem: typeof import('@tuniao/tnui-vue3-uniapp/components/form/src/form-item.vue')['default']
    TnIcon: typeof import('@tuniao/tnui-vue3-uniapp/components/icon/src/icon.vue')['default']
    TnInput: typeof import('@tuniao/tnui-vue3-uniapp/components/input/src/input.vue')['default']
    TnListItem: typeof import('@tuniao/tnui-vue3-uniapp/components/list/src/list-item.vue')['default']
    TnLoading: typeof import('@tuniao/tnui-vue3-uniapp/components/loading/src/loading.vue')['default']
    TnLoadmore: typeof import('@tuniao/tnui-vue3-uniapp/components/loadmore/src/loadmore.vue')['default']
    TnNavbar: typeof import('@tuniao/tnui-vue3-uniapp/components/navbar/src/navbar.vue')['default']
    TnPhotoAlbum: typeof import('@tuniao/tnui-vue3-uniapp/components/photo-album/src/photo-album.vue')['default']
    TnPopup: typeof import('@tuniao/tnui-vue3-uniapp/components/popup/src/popup.vue')['default']
    TnScrollList: typeof import('@tuniao/tnui-vue3-uniapp/components/scroll-list/src/scroll-list.vue')['default']
    TnSwiper: typeof import('@tuniao/tnui-vue3-uniapp/components/swiper/src/swiper.vue')['default']
    WdButton: typeof import('wot-design-uni/components/wd-button/wd-button.vue')['default']
    WdIcon: typeof import('wot-design-uni/components/wd-icon/wd-icon.vue')['default']
    WdLoading: typeof import('wot-design-uni/components/wd-loading/wd-loading.vue')['default']
  }
}
