/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ComLoadmore: typeof import('./components/com-loadmore.vue')['default']
    EmptyComponents: typeof import('./components/empty-components.vue')['default']
    EmptyPopup: typeof import('./components/empty-popup.vue')['default']
    EmptyPopupNut: typeof import('./components/empty-popup-nut.vue')['default']
    EmptyPopupTn: typeof import('./components/empty-popup-tn.vue')['default']
    Layout: typeof import('./components/layout.vue')['default']
    NoData: typeof import('./components/no-data.vue')['default']
    TitleBar: typeof import('./components/title-bar.vue')['default']
    TnButton: typeof import('@tuniao/tnui-vue3-uniapp/components/button/src/button.vue')['default']
    TnCheckbox: typeof import('@tuniao/tnui-vue3-uniapp/components/checkbox/src/checkbox.vue')['default']
    TnCheckboxGroup: typeof import('@tuniao/tnui-vue3-uniapp/components/checkbox/src/checkbox-group.vue')['default']
    TnEmpty: typeof import('@tuniao/tnui-vue3-uniapp/components/empty/src/empty.vue')['default']
    TnLoading: typeof import('@tuniao/tnui-vue3-uniapp/components/loading/src/loading.vue')['default']
    TnLoadmore: typeof import('@tuniao/tnui-vue3-uniapp/components/loadmore/src/loadmore.vue')['default']
    TnPopup: typeof import('@tuniao/tnui-vue3-uniapp/components/popup/src/popup.vue')['default']
  }
}
