/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ComLoadmore: typeof import('./components/com-loadmore.vue')['default']
    EmptyComponents: typeof import('./components/empty-components.vue')['default']
    EmptyPopup: typeof import('./components/empty-popup.vue')['default']
    Layout: typeof import('./components/layout.vue')['default']
    NoData: typeof import('./components/no-data.vue')['default']
    TitleBar: typeof import('./components/title-bar.vue')['default']
  }
}
